### ISSUE TITLE
configuration driven data collector

### ISSUE THREAD

**Issue by jgmize** [mozilla/ahab#2]

**Comment by jdumars** [comment]
To maximize the extensibility of AI processing, we need a model of data collection that remains source-agnostic.  Therefore we need to let the data itself drive the schema and normalization.  This means the AI consumer can try and make sense out of it through pattern or series recognition (best), or a format map consisting of a schema and metadata (less desirable) can be submitted alongside the data stream.  AI should begin forming what I call a "Net Branch Strategy" around the aggregate (more on this in another issue).  

To start this work, we need to decide if we want data admission to be dynamic or static.  While static is more expedient, dynamic will ideally save a tremendous amount of duplication later.  

The base analysis model will be concerned with ferreting out patterns and deviations, as well as probable next actions.  It should correlate adjacent data sets to help form the probable paths.  Also, it should have the notion of "concern" when baselines are shifting consistently away from established norms.

For a Kubernetes cluster, we should start with data from the metrics API, synchronize based on lowest-common increment frequency, and develop the processing framework around it.  Data types should roughly extrapolate to the typing of the variables on the code side (e.g. int, float, text).  AI should make a best effort to determine typing.  

All data needs to be serialized in some way, even in the form of data objects such as an image file.  For example, two very similar photographs would be known sequentially by % same and % different, leading to predict based on correlation what the third iteration would look like.  More specifically, are red pixels trending toward blue?  White toward black?  If every pixel in the image is given a probability that it will remain the same, which are most likely to change in the next observation?  Again, this goes to the Net Branch Strategy.

**Comment by jdumars** [comment]
![img_2587 jpg](https://user-images.githubusercontent.com/1085157/32333081-5e006e86-bfbd-11e7-8473-7e7f5124a0e7.JPG)

**Comment by jdumars** [comment]
Description of net branch strategy (NBS):

The model defines observation horizons which correspond to points of temporal change in ordered succession.  Horizons can be any distance apart in time, but the more time elapsed, the lower the predictive fidelity.  

The observation inception is any starting point for sequential analysis.  Comparative analysis can be performed across equal numbers of sequential horizons, but this is less predictive than understanding underlying causation.  

For example, you could collect the first 5 log lines generated  at 12:01am on the second Monday of December for 5 consecutive years, and this data would almost certainly have some commonality.  But, due to the large temporal skew, it's likely that the underlying ecosystem has changed in some significant way.  This of course provides a different set of observation horizons that can provide large-scale predictive analysis (at a similar temporal scale), but does very little to say what the next year's exact observation will be.  Those are statistically more likely to be the result of changes closer in time to the observation point.  If your last 5 birthdays were terrible, there's a good chance this one will be too, unless you take actions beforehand, or something unknown happens on the day to make it good.  

With repeated observations over time, the AI model begins assembling fragments of well-known deviations that follow a "normative path".  Think of this like a trail through the woods.  The more people hike the same trail, the more ruts form.  As they get deeper, or muddier, people start expanding to the side of it, and over time, the path widens.  During a rain storm, deep water may force hikers to go far around the ruts.  But, when it dries out, they will return closer to the interior of the path.  From a predictive standpoint, the center of the normative path represents the highest fidelity assuming the horizons and comparisons used to generate it were roughly comparable without a large temporal skew.  

Changes in the normative path can be represented in three ways: well-known, triggered, or transitional. 

Well-known deviations are those which happen in a cadence of meta-observations, and typically influenced by an interaction with another, related system.  Holidays are a great example of a cause for well-known deviations.  As are things like cron jobs, end-of-month reports, or ETL activities.

Triggered deviations are departures from the normative path caused by a sudden shift in some underlying or dependent factor in the ecosystem.  A power outage, network failure, or unplanned reboot could all cause a triggered deviation.  Because the "gravity" around the normative path is very high, it's likely that state will return to it.  If not, it represents the third form of deviation: transitional.

Transitional deviation represents the gradual (or sometimes sudden) shift of the normative path in one direction or another.  The gap between one normative path and another emerging one is described as "concern".  For example, in our bodies, we may have an injury in our arm, and over time, it gets weaker and weaker.  That is a concern, although it is not a purely negative qualifier.  If your arm gets stronger over time due to physical therapy, this is also a concern.   Both changes represent the establishment of a new normative path.  

Between any two adjacent horizons in any given scale, there exists a probability of it replicating a prior observation.  The model is based on an infinite scale ranging from 0 to 1 where zero represents an impossible outcome, and one represents absolute certainty.  The AI model is responsible for determining what can be compared to what.  Numerical data represents the easiest correlation, where qualitative horizons represent the hardest.  The relationship between 2 and 2.1 is easier to determine than a human describing how they feel today versus yesterday.  The NBS can accommodate any form of horizon, including purely subjective.  

An example of this model in action would be a series of "used disk space" horizons captured in a log file.  The update increment could be every second.  AI would adjust the normative path in real time, as well as assessing any of the three types of deviations at every observable point.  It would also pre-fetch any comparable horizons to assemble a model of predictive analysis.  At every horizon, it would check the difference between its expected/predicted change, and the observed change.  It would then adjust its probability ranking accordingly.   So, if it had an observation series of 501, 502, 503, 504, it might have a predictive certainty of .85 that the next observation will be 505, and .45 that it would be 504, and so forth for other possibilities.  If the model had determined that the most possible change between any two horizons was 10 (or N), then N+X values would be zero.  If something out of range happens, then N changes accordingly.  Over time, range values will become finely tuned around the normative path.  It not only helps increase the accuracy of prediction, it also lowers the number of calculations around each horizon.  

One goal of the model is to focus on only retaining pertinent data, so we capture anomalies and disregard the norm.  Of course, the norm will shift over horizons, so the more concern, the more "normal" data you have to keep and analyze.   The schema for NBS will depend on the source, but metadata should be relatively consistent.  The model must be able to expand based on observed phenomenon, so even the metadata must be dynamic.  Additionally, metadata will have its own horizons ("thinking about thinking").
